### ISSUE TITLE
Dirent parsing error

### ISSUE THREAD

**Issue by csabahenk** [gluster/parsefuse#1]
`READDIR` / `READDIRPLUS` is prone to this:

```
READDIRPLUS {Len:80 Opcode:44 Unique:8 Nodeid:1 Uid:1000 Gid:1000 Pid:14756 Padding:0} {Fh:140314971485260 Offset:0 Size:4096 ReadFlags:0 LockOwner:0 Flags:100352 Padding:0} 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.parsedir(0xc82009c600, 0x30, 0xfa00, 0xc80000002c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fedora/parsefuse/go/src/parsefuse/parsefuse.go:285 +0x698
main.main()
        /home/fedora/parsefuse/go/src/parsefuse/parsefuse.go:471 +0x1602
```

with Go 1.5.4.

**Comment by csabahenk** [comment]
The calculation of the size of the `Dirent` structure:

``` go
type Dirent struct {
        Ino     uint64
        Off     uint64
        Namelen uint32
        Type    uint32
        Name    [0]byte
}
```

does not give back the proper size with Go 1.5.4. (8 bytes are accounted for the `Name` field, which is expected (and used) to be 0). Hotfix: hardwire its size as follows:

``` diff
diff --git a/go/src/parsefuse/parsefuse.go b/go/src/parsefuse/parsefuse.go
index aab805b..6b1a13e 100644
--- a/go/src/parsefuse/parsefuse.go
+++ b/go/src/parsefuse/parsefuse.go
@@ -261,7 +261,7 @@ func (fmr *FUSEMsgReader20) readmsg() (dir byte, meta []interface{}, buf []byte)
 //

 const (
-   direntSize = int(unsafe.Sizeof(protogen.Dirent{}))
+   direntSize = 24
    entryoutSize = int(unsafe.Sizeof(protogen.EntryOut{}))
 )
```

**Comment by csabahenk** [comment]
Caused by Go changing behavior as of https://github.com/golang/go/commit/6f07ac2f280847ee0346b871b23cab90869f84a4 (`go1.5beta1~2396`). (Referenced from a similar issue https://github.com/golang/go/issues/11925.)
